# Site settings
title: George Zhao
description: 'Buiness Card Page'
url: 'http://zhaoyichina.github.com'
baseurl: ''
profilepic: '/images/me.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'George Zhao'
  email: 982670572@qq.com
  twitter_username: zhaoyichina
#  facebook_username: joshgerdes
  github_username:  tzuehlke
  linkedin_username:  赵毅
  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
